### ISSUE TITLE
Replace dep with Go Modules

### ISSUE THREAD

**Issue by VoyTechnology** [terra-farm/terraform-provider-virtualbox#38]
Originally I have created #30, which was the most up to date dependency management software at the time. But since then [Go Modules][1] came out. Go 1.11 added preliminary support for it, so I think we should look at potentially replacing dep with it.

Below are the steps which are necessary to make go modules work and deprecate go dep.

- [x] Add `go.mod` files to the repo - #36
- [x] Use Go 1.11.4 in Travis - #37 
- [x] Switch to use go modules in `.travis.yml` - #43 
- [x] Remove `Gopkg.toml` and `Gopkg.lock` - 8af001e

[1]: https://github.com/golang/go/wiki/Modules

**Comment by ringods** [comment]
Contributions to Go 1.11 welcome! I want the providers to be in shape by the time TF 0.12 is released. Looking in the TF 0.12 dev branch, Go 1.11 is dependency there.

**Comment by VoyTechnology** [comment]
Technically we can switch to Go modules in Travis anyways, as it is not depending on any development workflow.

This transition period is a bit awkward, but I will soon update all dependencies, and will make sure that both `dep` and `mod` are covered.

**Comment by VoyTechnology** [comment]
Updated the issue body, as #43 does stage 3 of the migration.

**Comment by ringods** [comment]
@VoyTechnology I dropped the `dep` setup in commit 8af001e. We are now fully on `go` modules for the virtualbox provider and wrapper library.
